/*
 * Copyright Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags and
 * the COPYRIGHT.txt file distributed with this work.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was modified as part of the Kubling project.
 */

package com.kubling.client;

import com.kubling.core.KublingProcessingException;
import com.kubling.core.util.UnitTestUtil;
import com.kubling.netty.handler.codec.serialization.CompactObjectInputStream;
import org.junit.jupiter.api.Test;

import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SuppressWarnings("nls")
public class TestRequestMessage {

    public static RequestMessage example() {
        RequestMessage message = new RequestMessage();
        message.setStatementType(RequestMessage.StatementType.CALLABLE);
        message.setFetchSize(100);
        List<Integer> params = new ArrayList<>();
        params.add(100);
        params.add(200);
        params.add(300);
        params.add(400);
        message.setParameterValues(params);
        message.setParameterTypes(Arrays.asList(
                new ParameterType(Types.INTEGER, "integer"), null, null, null));

        message.setPartialResults(true);
        message.setStyleSheet("myStyleSheet");
        message.setExecutionPayload("myExecutionPayload");
        try {
            message.setTxnAutoWrapMode(RequestMessage.TXN_WRAP_ON);
        } catch (KublingProcessingException e) {
            throw new RuntimeException(e);
        }

        message.setShowPlan(RequestMessage.ShowPlan.ON);
        message.setRowLimit(1313);
        message.setReturnAutoGeneratedKeys(true);
        message.setDelaySerialization(true);
        message.setSupportsMultipleResults(true);
        message.setSpanContext("foo");
        return message;
    }

    @Test
    public void testSerialize() throws Exception {
        RequestMessage copy = UnitTestUtil.helpSerialize(example());

        assertTrue(copy.isCallableStatement());
        assertEquals(100, copy.getFetchSize());
        assertNotNull(copy.getParameterValues());
        assertEquals(4, copy.getParameterValues().size());
        assertEquals(100, copy.getParameterValues().get(0));
        assertEquals(200, copy.getParameterValues().get(1));
        assertEquals(300, copy.getParameterValues().get(2));
        assertEquals(400, copy.getParameterValues().get(3));
        assertEquals(example().getParameterTypes(), copy.getParameterTypes());

        assertFalse(copy.isPreparedStatement());
        assertEquals("myStyleSheet", copy.getStyleSheet());
        assertEquals("myExecutionPayload", copy.getExecutionPayload());
        assertEquals(RequestMessage.TXN_WRAP_ON, copy.getTxnAutoWrapMode());
        assertEquals(RequestMessage.ShowPlan.ON, copy.getShowPlan());
        assertEquals(1313, copy.getRowLimit());
        assertTrue(copy.isReturnAutoGeneratedKeys());
        assertTrue(copy.isDelaySerialization());
        assertTrue(copy.supportsMultipleResults());
        assertEquals("foo", copy.getSpanContext());
    }

    @Test
    public void testSerializeBatchedParameterTypes() throws Exception {
        RequestMessage message = new RequestMessage("SELECT ?, ?");
        message.setBatchedUpdate(true);
        message.setParameterValues(List.of(
                Arrays.asList(null, null), Arrays.asList(null, null)));
        message.setBatchedParameterTypes(List.of(
                List.of(new ParameterType(Types.INTEGER, "integer"),
                        new ParameterType(Types.ARRAY, "integer[]")),
                Arrays.asList(null, new ParameterType(Types.OTHER, "geography"))));

        RequestMessage copy = UnitTestUtil.helpSerialize(message);

        assertEquals(message.getParameterValues(), copy.getParameterValues());
        assertEquals(message.getBatchedParameterTypes(), copy.getBatchedParameterTypes());
    }

    @Test
    public void testInvalidTxnAutoWrap() {
        RequestMessage rm = new RequestMessage();
        try {
            rm.setTxnAutoWrapMode("foo");
            fail("exception expected");
        } catch (KublingProcessingException e) {
            assertEquals("KBL20000 'FOO' is an invalid transaction autowrap mode.", e.getMessage());
        }
    }

    @Test
    public void test83() throws IOException, ClassNotFoundException {
        CompactObjectInputStream ois =
                new CompactObjectInputStream(new FileInputStream(UnitTestUtil.getTestDataFile("req.ser")),
                        RequestMessage.class.getClassLoader());
        RequestMessage rm = (RequestMessage) ois.readObject();
        ois.close();
        assertFalse(rm.isReturnAutoGeneratedKeys());
        assertFalse(rm.isDelaySerialization());
        assertFalse(rm.supportsMultipleResults());
        assertTrue(rm.getParameterTypes().isEmpty());
        assertTrue(rm.getBatchedParameterTypes().isEmpty());
    }

}
