/*
 * Copyright Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags and
 * the COPYRIGHT.txt file distributed with this work.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was modified as part of the Kubling project.
 */

package com.kubling.client;

import com.kubling.core.KublingProcessingException;
import com.kubling.core.util.ExternalizeUtil;
import com.kubling.jdbc.JDBCPlugin;
import com.kubling.jdbc.RequestOptions;

import java.io.*;
import java.util.*;


/**
 * Request Message, used by MMXStatement for submitting queries.
 */
public class RequestMessage implements Externalizable {

    @Serial
    private static final long serialVersionUID = -8678560713712091903L;

    private static final byte PARAMETER_TYPES_VERSION = 1;
    private static final byte MULTIPLE_RESULTS_CAPABILITY_VERSION = 1;

    private static final String SPAN_CONTEXT = "spanContext";

    private static final RequestOptions DEFAULT_REQUEST_OPTIONS = new RequestOptions();

    public static final int DEFAULT_FETCH_SIZE = 2048;

    /**
     * Transaction auto wrap constant - never wrap a command execution in a transaction
     */
    public static final String TXN_WRAP_OFF = "OFF";

    /**
     * Transaction auto wrap constant - always wrap commands in a transaction.
     */
    public static final String TXN_WRAP_ON = "ON";

    /**
     * Transaction auto wrap constant - checks if a command
     * requires a transaction and will be automatically wrap it.
     */
    public static final String TXN_WRAP_DETECT = "DETECT";

    public enum StatementType {
        PREPARED, CALLABLE, STATEMENT
    }

    public enum ResultsMode {
        RESULTSET, UPDATECOUNT, EITHER
    }

    public enum ShowPlan {
        ON, DEBUG, OFF
    }

    private String[] commands;
    private boolean isBatchedUpdate;
    private int fetchSize = DEFAULT_FETCH_SIZE;
    private int cursorType;
    private boolean partialResultsFlag;
    private StatementType statementType = StatementType.STATEMENT;
    private List<?> parameterValues;
    private List<ParameterType> parameterTypes;
    private List<List<ParameterType>> batchedParameterTypes;
    private String txnAutoWrapMode;
    private String styleSheet;
    private ResultsMode resultsMode = ResultsMode.EITHER;
    //whether to use ResultSet cache if there is one
    private boolean useResultSetCache;
    // Treat the double-quoted strings as variables in the command
    private boolean ansiQuotedIdentifiers = true;
    private ShowPlan showPlan = ShowPlan.OFF;
    private int rowLimit;
    private Serializable executionPayload;
    private long executionId;
    private int transactionIsolation;
    private boolean noExec;
    private boolean autoGeneratedKeys;
    private boolean delaySerialization;
    private boolean supportsMultipleResults;

    /*
     * Used by embedded connections, could change if we add support
     * for an async socket transport
     */
    private boolean sync;
    private RequestOptions requestOptions;
    private Object command;

    private Map<String, String> properties;

    public RequestMessage() {
    }

    public RequestMessage(String command) {
        this();
        setCommands(command);
    }

    public boolean isSync() {
        return sync;
    }

    public void setSync(boolean sync) {
        this.sync = sync;
    }

    public int getFetchSize() {
        return fetchSize;
    }

    public boolean supportsPartialResults() {
        return partialResultsFlag;
    }

    public void setFetchSize(int fetchSize) {
        this.fetchSize = fetchSize;
    }

    public void setPartialResults(boolean partial) {
        partialResultsFlag = partial;
    }

    /**
     * @return True if this request includes a prepared statement.
     */
    public boolean isPreparedStatement() {
        return this.statementType == StatementType.PREPARED;
    }

    /**
     * @return True if this request includes a callable statement.
     */
    public boolean isCallableStatement() {
        return this.statementType == StatementType.CALLABLE;
    }

    public void setStatementType(StatementType statementType) {
        this.statementType = statementType;
    }

    /**
     * @return A list of parameter values. May be null.
     */
    public List<?> getParameterValues() {
        if (parameterValues == null) {
            return Collections.EMPTY_LIST;
        }
        return parameterValues;
    }

    public void setParameterValues(List<?> values) {
        parameterValues = values;
    }

    /**
     * Returns type metadata parallel to {@link #getParameterValues()} for a
     * non-batched prepared statement. A null entry means that the parameter
     * has no explicit type metadata.
     */
    public List<ParameterType> getParameterTypes() {
        if (parameterTypes == null) {
            return Collections.emptyList();
        }
        return parameterTypes;
    }

    public void setParameterTypes(List<ParameterType> parameterTypes) {
        this.parameterTypes = parameterTypes;
    }

    /**
     * Returns type metadata parallel to the rows in
     * {@link #getParameterValues()} for a batched prepared statement.
     */
    public List<List<ParameterType>> getBatchedParameterTypes() {
        if (batchedParameterTypes == null) {
            return Collections.emptyList();
        }
        return batchedParameterTypes;
    }

    public void setBatchedParameterTypes(List<List<ParameterType>> batchedParameterTypes) {
        this.batchedParameterTypes = batchedParameterTypes;
    }

    /**
     * @return String
     */
    public int getCursorType() {
        return cursorType;
    }

    /**
     * Sets the cursorType.
     *
     * @param cursorType The cursorType to set
     */
    public void setCursorType(int cursorType) {
        this.cursorType = cursorType;
    }

    /**
     * @return String
     */
    public String getTxnAutoWrapMode() {
        if (txnAutoWrapMode == null) {
            return TXN_WRAP_DETECT;
        }
        return txnAutoWrapMode;
    }

    /**
     * Sets the txnAutoWrapMode.
     *
     * @param txnAutoWrapMode The txnAutoWrapMode to set
     */
    public void setTxnAutoWrapMode(String txnAutoWrapMode) throws KublingProcessingException {
        if (txnAutoWrapMode != null) {
            txnAutoWrapMode = txnAutoWrapMode.toUpperCase();
            if (!(txnAutoWrapMode.equals(TXN_WRAP_OFF)
                    || txnAutoWrapMode.equals(TXN_WRAP_ON)
                    || txnAutoWrapMode.equals(TXN_WRAP_DETECT))) {
                throw new KublingProcessingException(JDBCPlugin.Event.KBL20000,
                        JDBCPlugin.Util.gs(JDBCPlugin.Event.KBL20000, txnAutoWrapMode));
            }
        }
        this.txnAutoWrapMode = txnAutoWrapMode;
    }

    /**
     * @return String
     */
    public String getStyleSheet() {
        return styleSheet;
    }

    /**
     * Sets the styleSheet.
     *
     * @param styleSheet The styleSheet to set
     */
    public void setStyleSheet(String styleSheet) {
        this.styleSheet = styleSheet;
    }

    public boolean useResultSetCache() {
        return useResultSetCache;
    }

    public void setUseResultSetCache(boolean useResultSetCache) {
        this.useResultSetCache = useResultSetCache;
    }

    public String getCommandString() {
        if (commands.length == 1) {
            return commands[0];
        }
        return Arrays.deepToString(commands);
    }

    public boolean isAnsiQuotedIdentifiers() {
        return ansiQuotedIdentifiers;
    }

    public void setAnsiQuotedIdentifiers(boolean ansiQuotedIdentifiers) {
        this.ansiQuotedIdentifiers = ansiQuotedIdentifiers;
    }

    public ShowPlan getShowPlan() {
        return showPlan;
    }

    public void setShowPlan(ShowPlan showPlan) {
        this.showPlan = showPlan;
    }

    /**
     * @return Returns the rowLimit.
     * @since 4.3
     */
    public int getRowLimit() {
        return this.rowLimit;
    }


    /**
     * @param rowLimit The rowLimit to set.
     * @since 4.3
     */
    public void setRowLimit(int rowLimit) {
        this.rowLimit = rowLimit;
    }

    public String[] getCommands() {
        return commands;
    }

    public void setCommands(String... batchedCommands) {
        this.commands = batchedCommands;
    }

    public Object getCommand() {
        return command;
    }

    public void setCommand(Object command) {
        this.command = command;
    }

    public void setExecutionPayload(Serializable executionPayload) {
        this.executionPayload = executionPayload;
    }

    public Serializable getExecutionPayload() {
        return executionPayload;
    }

    public long getExecutionId() {
        return executionId;
    }

    public void setExecutionId(long executionId) {
        this.executionId = executionId;
    }

    public void setBatchedUpdate(boolean isBatchedUpdate) {
        this.isBatchedUpdate = isBatchedUpdate;
    }

    public boolean isBatchedUpdate() {
        return isBatchedUpdate;
    }

    public ResultsMode getResultsMode() {
        return resultsMode;
    }

    public void setResultsMode(ResultsMode resultsMode) {
        this.resultsMode = resultsMode;
    }

    public int getTransactionIsolation() {
        return transactionIsolation;
    }

    public void setTransactionIsolation(int transactionIsolation) {
        this.transactionIsolation = transactionIsolation;
    }

    public boolean isNoExec() {
        return noExec;
    }

    public void setNoExec(boolean noExec) {
        this.noExec = noExec;
    }

    @Override
    public void readExternal(ObjectInput in) throws IOException,
            ClassNotFoundException {
        this.commands = ExternalizeUtil.readStringArray(in);
        this.isBatchedUpdate = in.readBoolean();
        this.fetchSize = in.readInt();
        this.cursorType = in.readInt();
        this.partialResultsFlag = in.readBoolean();
        this.statementType = StatementType.values()[in.readByte()];
        this.parameterValues = ExternalizeUtil.readList(in);
        in.readBoolean(); //legacy validation mode
        this.txnAutoWrapMode = (String) in.readObject();
        in.readObject(); // legacy xml format
        this.styleSheet = (String) in.readObject();
        this.resultsMode = ResultsMode.values()[in.readByte()];
        this.useResultSetCache = in.readBoolean();
        this.ansiQuotedIdentifiers = in.readBoolean();
        this.showPlan = ShowPlan.values()[in.readByte()];
        this.rowLimit = in.readInt();
        this.executionPayload = (Serializable) in.readObject();
        this.executionId = in.readLong();
        this.transactionIsolation = in.readInt();
        this.noExec = in.readBoolean();
        try {
            byte options = in.readByte();
            //8.3 property
            this.autoGeneratedKeys = (options & 1) == 1;
            //8.4 property
            this.delaySerialization = (options & 2) == 2;
            this.properties = ExternalizeUtil.readMap(in);

            try {
                byte parameterTypesVersion = in.readByte();
                if (parameterTypesVersion == PARAMETER_TYPES_VERSION) {
                    if (isBatchedUpdate) {
                        this.batchedParameterTypes = readBatchedParameterTypes(in);
                    } else {
                        this.parameterTypes = readParameterTypes(in);
                    }
                }
            } catch (OptionalDataException | EOFException e) {
                // Parameter type metadata was added after the original wire format.
            }
            try {
                byte multipleResultsVersion = in.readByte();
                if (multipleResultsVersion == MULTIPLE_RESULTS_CAPABILITY_VERSION) {
                    supportsMultipleResults = in.readBoolean();
                }
            } catch (OptionalDataException | EOFException e) {
                // Multiple-result negotiation was added after the original wire format.
            }
        } catch (OptionalDataException | EOFException e) {
            // Ignored
        }
    }

    @Override
    public void writeExternal(ObjectOutput out) throws IOException {
        ExternalizeUtil.writeArray(out, commands);
        out.writeBoolean(isBatchedUpdate);
        out.writeInt(fetchSize);
        out.writeInt(cursorType);
        out.writeBoolean(partialResultsFlag);
        out.writeByte(statementType.ordinal());
        ExternalizeUtil.writeList(out, parameterValues);
        out.writeBoolean(false); //legacy xml validation
        out.writeObject(txnAutoWrapMode);
        out.writeObject(null); //legacy xml format
        out.writeObject(styleSheet);
        out.writeByte(resultsMode.ordinal());
        out.writeBoolean(useResultSetCache);
        out.writeBoolean(ansiQuotedIdentifiers);
        out.writeByte(showPlan.ordinal());
        out.writeInt(rowLimit);
        out.writeObject(executionPayload);
        out.writeLong(executionId);
        out.writeInt(transactionIsolation);
        out.writeBoolean(noExec);
        byte options = 0;
        if (autoGeneratedKeys) {
            options |= 1;
        }
        if (delaySerialization) {
            options |= 2;
        }
        out.writeByte(options);
        ExternalizeUtil.writeMap(out, properties);
        out.writeByte(PARAMETER_TYPES_VERSION);
        if (isBatchedUpdate) {
            writeBatchedParameterTypes(out, batchedParameterTypes);
        } else {
            writeParameterTypes(out, parameterTypes);
        }
        out.writeByte(MULTIPLE_RESULTS_CAPABILITY_VERSION);
        out.writeBoolean(supportsMultipleResults);
    }

    private static void writeBatchedParameterTypes(ObjectOutput out,
                                                   List<List<ParameterType>> batchedTypes)
            throws IOException {
        if (batchedTypes == null) {
            out.writeInt(0);
            return;
        }
        out.writeInt(batchedTypes.size());
        for (List<ParameterType> types : batchedTypes) {
            writeParameterTypes(out, types);
        }
    }

    private static List<List<ParameterType>> readBatchedParameterTypes(ObjectInput in)
            throws IOException {
        int size = in.readInt();
        List<List<ParameterType>> result = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            result.add(readParameterTypes(in));
        }
        return result;
    }

    private static void writeParameterTypes(ObjectOutput out, List<ParameterType> types)
            throws IOException {
        if (types == null) {
            out.writeInt(0);
            return;
        }
        out.writeInt(types.size());
        for (ParameterType type : types) {
            out.writeBoolean(type != null);
            if (type != null) {
                out.writeInt(type.getJdbcType());
                String typeName = type.getTypeName();
                out.writeBoolean(typeName != null);
                if (typeName != null) {
                    out.writeUTF(typeName);
                }
            }
        }
    }

    private static List<ParameterType> readParameterTypes(ObjectInput in)
            throws IOException {
        int size = in.readInt();
        List<ParameterType> result = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            if (!in.readBoolean()) {
                result.add(null);
                continue;
            }
            int jdbcType = in.readInt();
            String typeName = in.readBoolean() ? in.readUTF() : null;
            result.add(new ParameterType(jdbcType, typeName));
        }
        return result;
    }

    public RequestOptions getRequestOptions() {
        if (this.requestOptions == null) {
            this.requestOptions = DEFAULT_REQUEST_OPTIONS;
        }
        return this.requestOptions;
    }

    public void setRequestOptions(RequestOptions requestOptions) {
        this.requestOptions = requestOptions;
    }

    public void setReturnAutoGeneratedKeys(boolean autoGenerateKeys) {
        this.autoGeneratedKeys = autoGenerateKeys;
    }

    public boolean isReturnAutoGeneratedKeys() {
        return this.autoGeneratedKeys;
    }

    public boolean isDelaySerialization() {
        return delaySerialization;
    }

    public void setDelaySerialization(boolean delaySerialization) {
        this.delaySerialization = delaySerialization;
    }

    /**
     * Determine whether the client can consume an ordered sequence of JDBC
     * results for this request.
     *
     * @return {@code true} when the multiple-results protocol is supported
     */
    public boolean supportsMultipleResults() {
        return supportsMultipleResults;
    }

    /**
     * Advertise that the client can consume an ordered sequence of JDBC
     * results for this request.
     *
     * @param supportsMultipleResults whether the protocol extension is supported
     */
    public void setSupportsMultipleResults(boolean supportsMultipleResults) {
        this.supportsMultipleResults = supportsMultipleResults;
    }

    public void setSpanContext(String string) {
        if (this.properties == null) {
            this.properties = new HashMap<>();
        }
        if (string == null) {
            this.properties.remove(SPAN_CONTEXT);
        } else {
            properties.put(SPAN_CONTEXT, string);
        }
    }

    public String getSpanContext() {
        if (this.properties == null) {
            return null;
        }
        return this.properties.get(SPAN_CONTEXT);
    }

}
